### ISSUE TITLE
How-to handle the ListeOfDevices[nwkid]['Ep'][ep]['ClusterType'] 

### ISSUE THREAD

**Issue by zigbeefordomoticz** [zigbeefordomoticz/test_domoticzex#1]
['ClusterType'] is a dict which store a 'Domoticz Device ID' and the corresponding 'ClusterType'.

In the legacy framework, the DeviceID is given my the .Create() looks like with the ExtendedFramework it is not.

Legacy framework
`Device ID: 2, Name: 'Test DomoticzEx - Counter_1', nValue: 0, sValue: ''`

Extended framework
`Unit: 1, Name: 'Counter_2', nValue: 0, sValue: '', LastUpdate: 2023-09-19 11:09:53`

**Comment by pipiche38** [comment]
| Members |  Legacy                                                                                       | Extended                                                            |
| ---------  | ---------------------------------------------------------- |  -------------------------------------------- |
| Name       |  Current Name in Domoticz  (RW)                                            |  initial Domoticz Device name                          |
| DeviceID  |  External device identifier  Auto-generated at Create() time | Set the DeviceID to be used with the device. |
| Unit          | Plugin index for the Device. given at Create() time                | Plugin index for the Device.                             |
| ID             | The Domoticz Device ID                                                           |  The Domoticz Device ID   |

**Comment by pipiche38** [comment]
return Devices[DeviceID].Units[Unit].ID

fix in https://github.com/zigbeefordomoticz/test_domoticzex/commit/bf074be2f7d82e1ce9cc2b2edff701a938930863
